### ISSUE TITLE
Schema for annotations?

### ISSUE THREAD

**Issue by StevenBonePgh** [JetBrains/ExternalAnnotations#128]
I am building annotations for an internal package. The starting point is to use the process of launching visual studio with a /ReSharper.Internal argument, assure the project is in the root folder of the solution then use the menus ReSharper | Internal | Tools | Annotator | Export Source Annotations to XML to export them.  The file looks similar to those in this repository, but Resharper is throwing an exception "BuildIndexForFile" "Tag argument unexpected" with a stacktrace like below:
```
at JetBrains.ReSharper.Psi.Impl.Reflection2.ExternalAnnotations.XmlPsiScanner.TagScanner.ParseTag(XmlReader reader)
     at JetBrains.ReSharper.Psi.Impl.Reflection2.ExternalAnnotations.XmlPsiScanner.TagScanner.ParseTag(XmlReader reader)
     at JetBrains.ReSharper.Psi.Impl.Reflection2.ExternalAnnotations.XmlPsiScanner.Process(XmlReader reader)
     at JetBrains.ReSharper.Psi.Impl.Reflection2.ExternalAnnotations.AnnotationsIndexBuilder.BuildIndexForFile(XmlReader lexer)
```
I assumed this GitHub project would have a validator or schema for the annotations to assure they are parsable. I suppose I'd also assume that the internal tool would create parsable files as well.  Is there a schema somewhere or a mechanism of determining exactly what the unexpected tag is?

**Comment by NN---** [comment]
Opened: https://youtrack.jetbrains.com/issue/RSRP-473619
